"""empty message

Revision ID: 66698b144555
Revises: c284618e2a3b
Create Date: 2020-09-22 23:55:49.687377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66698b144555'
down_revision = 'c284618e2a3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cadastro', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cadastro')
    # ### end Alembic commands ###
