"""empty message

Revision ID: 74a9441bc4b7
Revises: 66698b144555
Create Date: 2020-09-23 00:59:29.112132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74a9441bc4b7'
down_revision = '66698b144555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.String(length=128), nullable=False))
    op.drop_column('users', 'endereco')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('endereco', mysql.VARCHAR(length=128), nullable=False))
    op.drop_column('users', 'address')
    # ### end Alembic commands ###
