"""empty message

Revision ID: 8cfa71e46c2d
Revises: 74a9441bc4b7
Create Date: 2020-09-23 01:03:07.303374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8cfa71e46c2d'
down_revision = '74a9441bc4b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lastname', sa.String(length=32), nullable=True))
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', mysql.VARCHAR(length=32), nullable=True))
    op.drop_column('users', 'lastname')
    # ### end Alembic commands ###
