"""empty message

Revision ID: c284618e2a3b
Revises: 
Create Date: 2020-09-22 22:56:40.833031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c284618e2a3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tel', sa.String(length=14), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('cpf', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('passwd', sa.String(length=512), nullable=False),
    sa.Column('estado', sa.String(length=64), nullable=False),
    sa.Column('cidade', sa.String(length=64), nullable=True),
    sa.Column('endereco', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('nascimento', sa.Date(), nullable=False),
    sa.Column('conf_tel', sa.Boolean(), nullable=True),
    sa.Column('conf_email', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
